# Inference Pipeline

# Purpose: Reuse the .pkl model and consume the live_stream.csv data in real time

import pandas as pd
import joblib
import os 

# configuration: Path to the saved intelligence
MODEL_PATH = "models/vibration_classifier_v1.pkl"
DATA_PATH = "data/live_stream.csv"

def load_ai_model():
    # loads the pre-trained Random Forest model
    try:
        model = joblib.load(MODEL_PATH)
        return model
    except Exception as e:
        print(f"Error loading model: {e}")
        return None
    
def get_latest_data():
    # Reads the latest single frame from the C++ Engine
    if not os.path.exists(DATA_PATH):
        return None
    
    try:
        # Read the csv data generated by the C++ while(true) loop
        df = pd.read_csv(DATA_PATH)
        return df
    except Exception:
        # if C++ is writing at the exact same time, we just return None and try again
        return None
    
def run_inference(model, input_df):
    # Bridge the raw data to the AI model so that it can generate the prediction
    if model is None or input_df is None:
        return None

    # Select only the features the model was trained on
    features = input_df[['smooth_freq', 'smooth_mag']]

    # The AI returns 0 (safe) or 1 (danger)
    prediction = model.predict(features)

    # Adding the prediction back to our data frame for the UI to use later
    input_df['ai_prediction'] = prediction
    return input_df